### ISSUE TITLE
ConoHaのポート制限調査

### ISSUE THREAD

**Issue by aoitan** [FxOS-Code-Reading-Group/MainRepo#11]
ConoHaにポート制限があるか調べる

**Comment by aoitan** [comment]
-   試用中だけ制限がある
-   コントロールパネルのFWの設定をいじる必要がある

　なのでポート解放の必要があったらIssue立ててあおいたんに依頼してください。

**Comment by MSakamaki** [comment]
今のところポートフリーダムに使えてるので、制限はなさそう。
