### ISSUE TITLE
ConoHaのドメイン

### ISSUE THREAD

**Issue by aoitan** [FxOS-Code-Reading-Group/MainRepo#4]
ConoHaで使うドメインの確保
-   浅井さんにfxos.orgのサブドメイン使えるか聞く

**Comment by aoitan** [comment]
浅井さんにサブドメイン使えるか聞いてる中。

**Comment by aoitan** [comment]
返答あり。サブドメインとレコードを連絡すれば借用可能。

　にしむらさんとさかまきさんが仕事したら
-   どのようなサブドメイン
-   どのようなレコード

　を決めて浅井さんに連絡する。

**Comment by aoitan** [comment]
A reading.fxos.org (IP)
で依頼した

**Comment by MSakamaki** [comment]
http://reading.fxos.org/ キテル
